# Generated by Django 5.1.6 on 2025-03-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='user',
        ),
    ]
