# Generated by Django 5.1.6 on 2025-03-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_remove_todomodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
