# Generated by Django 5.1.6 on 2025-03-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_alter_todomodel_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='details',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
